### ISSUE TITLE
Not able to run language_task.py

### ISSUE THREAD

**Issue by madhu-aithal** [nnRNN/nnRNN_release#4]
If I run language_task.py with cuda=True, I am getting the below error. I ran this after fixing some minor bugs in the file. I have also raised a PR for that. Please let me know how to fix this error.

```
Traceback (most recent call last):
  File "language_task.py", line 323, in <module>
    loss = train(optimizer, orthog_optimizer)
  File "language_task.py", line 266, in train
    output, hidden = model(data, hidden)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "language_task.py", line 93, in forward
    emb = self.encoder(input)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/sparse.py", line 117, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/functional.py", line 1506, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of backend CUDA but got backend CPU for argument #3 'index'
```

**Comment by KyleGoyette** [comment]
Looks like in my rush I commented a line which sets inputs to cuda in the batchify function of language_task. I'll fix that.
